version: '3.9'
services:
  # MongoDB services
  mongo_db:
   container_name: db_container
   image: mongo
   restart: always
   volumes:
    - ./mongo_db:/data/db

  # MongoDB services
  api: 
    build: .
    ports:
      - 3000:3000
    environment:
      API_KEY: ''
      DB_NAME: mongodb://mongo_db:27017/Bike-store
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}

 
 
 
 
